name: tag_field_example
description: Example app for tag_field
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints:
  tag_field:
    path: ../

flutter:
  uses-material-design: true
