name: tag_field
description: A customizable Flutter widget for adding and managing tags.
version: 1.0.0
homepage: https://github.com/yourname/tag_field # optional but recommended
repository: https://github.com/yourname/tag_field
issue_tracker: https://github.com/yourname/tag_field/issues
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - asset/
